#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#+     at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".

apt-get -y update
apt-get -y install nginx

#mkdir /etc/nginx/html
#touch /etc/nginx/html/index.html
#echo "Hello World!" > /etc/nginx/html/index.html
#touch /etc/nginx/html/404.html
#echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
echo "Hello World!" > /var/www/html/index.html

sed -i "/listen 80 default_server;/a\ \tadd_header X-Served-By $hostname;" /etc/nginx/sites-available/default

service nginx restart