#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

set -e

# Update package repositories and upgrade existing packages
apt-get -y update
apt-get -y upgrade

# Install HAProxy
apt-get -y install haproxy

# Enable HAProxy management via init script
echo "ENABLED=1" >> /etc/default/haproxy

# Backup the original HAProxy configuration file
mv /etc/haproxy/haproxy.cfg{,.original}

# Define the template for HAProxy configuration
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 3.84.239.19:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 500126-web-01 54.210.196.197:80 check
    server 500126-web-02 100.25.144.162:80 check
EOF

# Restart HAProxy using systemctl
systemctl restart haproxy
